services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules # prevent overwriting node_modules
    command: nodemon server.js
    depends_on:
      - bert

  bert:
    build:
      context: ./backend
      dockerfile: Dockerfile.bert
    ports:
      - "7455:7455"
    volumes:
      - ./backend:/app
    command: flask --app main.py --host=0.0.0.0 --port=7455 --reload
